version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=tg_db
      - POSTGRES_USER=tg_user
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=tg_pass
    volumes:
      - pgdata:/var/lib/posgresql/data
  web:
    build: .
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/code/static
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  pgdata:
  static_volume:
